---
# list of applications to install
general:
  local_home: "{{ lookup('env','HOME') }}"

# homebrew applications
applications:
  - git
  - tree
  - curl
  - wget
  - zsh

# homebrew cask applications
cask_applications:
  - google-chrome
  - caffeine
  - spotify
  - checkra1n

downloads:
   zwift:
     name: Zwift
     url: http://cdn.zwift.com/app/ZwiftOSX.dmg
     dest: "{{general.local_home}}/Downloads/ZwiftOSX.dmg"
#   zwift:
#     name: Zwift
#     url: http://cdn.zwift.com/app/ZwiftOSX.dmg
#     dest: "{{general.local_home}}/Downloads/ZwiftOSX.dmg"


